# Generated by Django 4.2.3 on 2023-08-01 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartitem',
            table='CartItem',
        ),
    ]
